In [1]:
import numpy as np

In [2]:
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
print("Dimension of array=", arr.ndim)

Dimension of array= 2


In [3]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
print("Shape of array=", arr.shape)

Shape of array= (3, 3)


In [5]:
import numpy as np
arr=np.zeros((2,3))
arr



array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
import numpy as np
arr=np.zeros(4)
arr



array([0., 0., 0., 0.])

In [7]:
import numpy as np
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

In [8]:
import numpy as np
arr=np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
import numpy as np
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
import numpy as np
arr=np.diag([2,3,4,5])
arr

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [11]:
import numpy as np
arr=np.diag([2,3,4,5])
np.diag(arr)

array([2, 3, 4, 5])

In [12]:
import numpy as np
arr=np.random.randint(1,10,3)
arr

array([8, 7, 1])

In [13]:
import numpy as np
arr=np.random.randint(1,10,3)
arr


array([2, 1, 3])

In [14]:
import numpy as np
arr=np.random.randint(1,10,3)
arr

array([1, 4, 7])

In [15]:
import numpy as np
arr=np.random.rand(5)
arr

array([0.25392738, 0.43557427, 0.66105593, 0.53053459, 0.18534487])

In [20]:
import numpy as np
arr=np.random.rand(2,3)
arr


array([[0.42945367, 0.12629852, 0.97176357],
       [0.97993693, 0.35546001, 0.20366781]])

In [21]:
v2 = np.arange(24).reshape(2,3,4) 
print(v2)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [22]:
v3 = np.array([(1,2,3)])
print(v3.itemsize)


4


In [23]:
v4=np.array([(3,2,3,4),(3,4,5,6)])
print(v4[0:,3])


[4 6]


In [24]:
v8=np.array([(1,2,3,4),(3,5,6,6)])
print(v8[0:,2])

[3 6]


In [25]:
v13 = np.array([1,2,3,4,7,9])
print(v13.max())


9


In [26]:
a = np.array([(1,2,3),(4,5,6)])

In [27]:
print(np.std(a))


1.707825127659933


In [28]:
v11 = np.array([[1,4],[3,1]])
np.sort(v11)


array([[1, 4],
       [1, 3]])

In [29]:
v12 = np.array([[5, 9, 6, 0],
              [6, 3, 7, 22]])
np.ptp(v12, axis=1)

array([ 9, 19])

In [30]:
v13 = np.array([1,2,3,4,7,9])
print(v13.max())


9


In [31]:
v13 = np.array([1,2,3,4,7,9])
print(v13.max())

9


In [32]:
a = np.array([1,2,0,3])
print(a.min())

0


In [33]:
v14= np.array([(1,3,3),(3,4,5)])
print(v14.ravel())



[1 3 3 3 4 5]


In [34]:
v15 = np.repeat(4, 2)
print(v14)

[[1 3 3]
 [3 4 5]]


In [35]:
v16 = np.array([[1,2],[3,4]])
print(np.repeat(v16, 2))



[1 1 2 2 3 3 4 4]


In [36]:
import numpy as np
arr=np.array([10,20,30,40])
np.cos(arr)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806])

In [37]:
import numpy as np
arr=np.array([10,20,30,40])
np.sin(arr)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [40]:
import numpy as np
arr=np.array([10,20,30,40])
np.tan(arr)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493])

In [41]:
import numpy as np
arr=np.array([10,20,30,40])
np.argmin(arr)

0

In [42]:
import numpy as np
arr=np.array([10,20,30,40])
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [43]:
import numpy as np
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [44]:
import numpy as np
np.linspace(1,72,5)

array([ 1.  , 18.75, 36.5 , 54.25, 72.  ])

In [45]:
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9)

In [51]:
matrix

array([16, 11, 13, 17, 13, 16,  3, 16, 11])

In [54]:
import numpy as np
arr=np.array([10,20,30,40])
np.unique(arr)

array([10, 20, 30, 40])